inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'lib/http/2/huffman_statemachine.rb'
    - 'vendor/**/*.rb' # see https://github.com/rubocop/rubocop/issues/9832

Gemspec/RequireMFA:
  Enabled: false

Metrics:
  Exclude:
    - 'spec/**/*.rb'

# For some reason, Metrics disable doesn't cover this
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
