inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'lib/http/2/huffman_statemachine.rb'

Gemspec/RequireMFA:
  Enabled: false