module HTTP2
  class FrameBuffer
    attr_reader bytesize: Integer

    @buffer: Array[data_frame]

    def clear: () -> void

    def <<: (data_frame_props frame) -> void

    def empty?: () -> bool

    def retrieve: (Integer) -> data_frame_props?
  end
end