module HTTP2Next
  class Server < Connection

    def upgrade: (String settings, Enumerable[header_pair] headers, String body) -> void

    def origin_set=: (Array[_ToS]) -> void

    private

    def promise: (Stream parent, Enumerable[header_pair] headers, Array[Symbol] flags) { (Stream) -> void } -> void
  end
end