module HTTP2
  module Header
    class Decompressor
      include BufferUtils

      FORBIDDEN_HEADERS: Array[String]
      DEFAULT_MAX_HEADER_LIST_SIZE: Integer

      @cc: EncodingContext
      @max_header_list_size: Integer

      def table_size=: (Integer) -> void
      def table_size_limit=: (Integer) -> void
      def max_header_list_size=: (Integer) -> void

      def integer: (String, Integer) -> Integer

      def string: (String) -> String

      def header: (String) -> header_command

      def decode: (String, frame?) -> Array[header_pair]
                | (String) -> Array[header_pair]
      private

      def initialize: (?connection_opts options) -> void
    end
  end
end
