module HTTP2Next
  module Header
    class Decompressor
      @cc: EncodingContext

      def table_size=: (Integer) -> void

      def integer: (String, Integer) -> Integer

      def string: (String) -> String

      def header: (String) -> header_command

      def decode: (String, frame?) -> Array[header_pair]
                | (String) -> Array[header_pair]
      private

      def initialize: (context_hash options) -> untyped
                    | () -> untyped
    end
  end
end
