module HTTP2
  module Header
    class Decompressor
      include BufferUtils

      FORBIDDEN_HEADERS: Array[String]

      @cc: EncodingContext

      @accept_invalid_headers: bool

      attr_writer max_header_list_size: Integer

      def max_table_size=: (Integer) -> void

      def integer: (String, Integer) -> Integer

      def string: (String) -> String

      def header: (String) -> (change_table_size_command | header_command)

      def decode: (String, frame?) -> Array[header_pair]
                | (String) -> Array[header_pair]

      def accept_invalid_headers!: () -> void

      private

      def initialize: (?Settings settings) -> void
    end
  end
end
