name: CI

on:
  pull_request:
    branches:
      - main
      - master

env:
  ruby_version: 3.3

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2, 3.3, jruby-9.4]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Tests
        run: |
          RUBY_PLATFORM=`ruby -e 'puts RUBY_PLATFORM'`
          RUBY_ENGINE=`ruby -e 'puts RUBY_ENGINE'`
          if [[ "$RUBY_ENGINE" = "ruby" ]] && [[ ${RUBY_VERSION:0:1} = "3" ]] && [[ ! $RUBYOPT =~ "jit" ]]; then
            echo "running runtime type checking..."
            export RUBYOPT="-rbundler/setup -rrbs/test/setup"
            export RBS_TEST_RAISE="true"
            export RBS_TEST_LOGLEVEL="error"
            export RBS_TEST_OPT="-Isig -rbase64"
            export RBS_TEST_TARGET="HTTP2Next*"
          fi
          ENV=CI bundle exec rake
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage-report
          path: coverage/

  coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@master
        with:
          name: coverage-report
          path: path/to/artifact

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: coverage
        run: |
          gem install simplecov --no-doc
          ls
          find coverage -name "*resultset.json" -exec sed -i 's?/home?'`pwd`'?' {} \;
          rake coverage:report

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage-report
          path: coverage/

  # pages:
  #   needs: coverage
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/download-artifact@master
  #       with:
  #         name: coverage-report
  #         path: path/to/artifact

  #     - name: publish
