name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, 3.3,
               jruby-9.0, jruby-9.1, jruby-9.2, jruby-9.3, jruby-9.4]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v4

      - name: Install gems
        run: |
          bundle config set --local without 'docs'
          bundle install

      - name: Tests
        run: ENV=CI bundle exec rake test
